Remove ZelbetWitnesses struct
dusk-network/zelbet pull request #45
Opened 2022-03-10 17:26 UTC by moCello

2022-03-11 13:38 UTC, vlopes11 requested changes

2022-03-11 13:38 UTC, vlopes11 commented on benches/hash.rs
> +    let one = composer.append_witness(BlsScalar::one());
nit
```suggestion
    let one = composer.append_witness(1);
```

2022-03-11 13:38 UTC, vlopes11 commented on examples/zelbet.rs
> +    let input = [BlsScalar::zero(), BlsScalar::one(), BlsScalar::from(42)];
nit: Add a comment saying this input is arbitrary

2022-03-11 13:38 UTC, vlopes11 commented on src/hash/zelbet_gadget/bar.rs
> +    witnesses[2] = composer.append_witness(BlsScalar::from(2));
These are constants and shouldn't be witnesses - otherwise a malicious prover might be able to tamper the proof.
```suggestion
    witnesses[1] = composer.append_constant(BlsScalar::one());
    witnesses[2] = composer.append_constant(BlsScalar::from(2));
```

2022-03-11 13:38 UTC, vlopes11 commented on src/hash/zelbet_gadget/bar.rs
> +                let one = composer.append_witness(BlsScalar::one());
Ditto; constant
```suggestion
                let one = composer.append_constant(BlsScalar::one());
```

2022-03-11 13:38 UTC, vlopes11 commented on src/hash/zelbet_gadget/bar.rs
> +                let one = composer.append_witness(BlsScalar::one());
Ditto; constant
```suggestion
                let one = composer.append_constant(BlsScalar::one());
```

2022-03-11 13:38 UTC, vlopes11 commented on src/hash/zelbet_gadget/bar.rs
> +                let witness = composer.append_witness(BlsScalar::one());
Ditto; constant
```suggestion
                let witness = composer.append_constant(BlsScalar::one());
```

2022-03-11 13:38 UTC, vlopes11 commented on src/hash/zelbet_gadget/bar.rs
> +                witnesses[2] = composer.append_witness(BlsScalar::from(2));
Ditto; constant
```suggestion
                witnesses[1] = composer.append_constant(BlsScalar::one());
                witnesses[2] = composer.append_constant(BlsScalar::from(2));
```

2022-03-11 13:38 UTC, vlopes11 commented on src/hash/zelbet_gadget/bar.rs
> +                witnesses[2] = composer.append_witness(BlsScalar::from(2));
Ditto; constants
```suggestion
                witnesses[1] = composer.append_constant(BlsScalar::one());
                witnesses[2] = composer.append_constant(BlsScalar::from(2));
```

2022-03-11 13:38 UTC, vlopes11 commented on src/sponge.rs
> +    mut input: Vec<Witness>,
We have no guarantee that the output size should be the same as the input. In fact, that is unlikely.
```suggestion
    input: &[Witness],
```

2022-03-11 13:38 UTC, vlopes11 commented on src/sponge.rs
>  ) -> Vec<Witness> {
The output length of the sponge function should be constant.

2022-03-11 13:38 UTC, vlopes11 commented on src/sponge.rs
> +    let one = composer.append_witness(BlsScalar::one());
Ditto; constant
```suggestion
    let one = composer.append_constant(BlsScalar::one());
```

2022-03-11 13:38 UTC, vlopes11 commented on tests/zelbet.rs
> +    let one = composer.append_witness(BlsScalar::one());
Ditto; constant
```suggestion
    let one = composer.append_constant(BlsScalar::one());
```

2022-03-12 16:40 UTC, xevisalle approved these changes
LGTM after addressing @vlopes11 's comments.

2022-03-14 16:47 UTC, moCello commented on src/sponge.rs
> +    mut input: Vec<Witness>,
The mutability is for the padding function. But I see that `sponge` needs closer attention. For now I reversed the changes in mutability of `input` (as it actually also not part of this PR anyway) and opened an issue for the changes in `sponge` #50

2022-03-16 12:12 UTC, vlopes11 requested changes

2022-03-16 12:12 UTC, vlopes11 commented on benches/hash.rs
> +    let one = composer.append_witness(1);
Previous review suggested `append_witness`, but it should be `append_constant`

2022-03-16 12:12 UTC, vlopes11 commented on src/hash/zelbet_gadget/bar.rs
> +                let one = composer.append_witness(BlsScalar::one());
Still pending

2022-03-16 12:12 UTC, vlopes11 commented on src/hash/zelbet_gadget/bar.rs
> +                let one = composer.append_witness(BlsScalar::one());
Still pending

2022-03-16 12:12 UTC, vlopes11 commented on src/hash/zelbet_gadget/bar.rs
> +                let witness = composer.append_witness(BlsScalar::one());
Still pending

2022-03-16 12:12 UTC, vlopes11 commented on src/hash/zelbet_gadget/bar.rs
> +                    composer.append_witness(BlsScalar::one());
Ditto; append constant

2022-03-16 12:12 UTC, vlopes11 commented on src/hash/zelbet_gadget/bar.rs
> +                    composer.append_witness(BlsScalar::one());
Ditto; append constant

2022-03-16 12:12 UTC, vlopes11 commented on src/sponge.rs
>  ) -> Vec<Witness> {
Still pending

2022-03-16 12:24 UTC, moCello commented on src/sponge.rs
>  ) -> Vec<Witness> {
The `output_len` of a sponge function is not always a constant. We can agree to set it to a constant for our purposes but I would like to keep that conversation out of this PR. I created #50 for it

2022-03-16 13:59 UTC, vlopes11 approved these changes
LGTM, just double check the comment I left

2022-03-16 13:59 UTC, vlopes11 commented on src/hash/zelbet_gadget/bar.rs
> +            y_i = composer.append_constant(S_BOX_BLS[x_i_value as usize]);
Be sure this `x_i_value` won't change depending on the witness

2022-03-21 10:50 UTC, moCello commented on src/hash/zelbet_gadget/bar.rs
> +            y_i = composer.append_constant(S_BOX_BLS[x_i_value as usize]);
It will! It needs to be a `witness` indeed, will change it back

2022-03-21 11:23 UTC, merged