Restructure modules
dusk-network/zelbet pull request #53
Opened 2022-03-23 14:00 UTC by moCello

With this change there are no modules with an underscore in their name

2022-03-23 14:21 UTC, vlopes11 requested changes
We are overusing aliases. If we are to restructure the modules, then the result should be clear enough to the point we don't need to consume the API with aliases

2022-03-23 14:21 UTC, vlopes11 commented on benches/hash.rs
> +use zelbet::sponge::{gadget as sponge_gadget, hash as sponge_hash};
I think its always better to use the native namespace. We should alias only if we have some name conflict, and that isn't the case here. If you feel the namespace isn't clear enough, then it would be worthy to change in its source instead of its usages.

2022-03-23 14:21 UTC, vlopes11 commented on examples/sponge.rs
> +use zelbet::sponge::gadget as sponge_gadget;
Ditto; stick to the intended API

2022-03-23 14:38 UTC, moCello commented on benches/hash.rs
> +use zelbet::sponge::{gadget as sponge_gadget, hash as sponge_hash};
In this case the functions `hash` and `gadget` can both refer to zelbet or its sponge functions. Do you think its better to rename the functions `zelbet::sponge::hash` and `zelbet::sponge::gadget` to `zelbet::sponge::sponge_hash` and `zelbet::sponge::sponge_gadget` respectively?

To be honest, I did these changes because @ZER0 wanted to eliminate the underscores in the module path names, so adding them back feels a bit weird.

2022-03-23 14:45 UTC, ZER0 requested changes

2022-03-23 14:45 UTC, ZER0 commented on benches/hash.rs
> +use zelbet::sponge::{gadget as sponge_gadget, hash as sponge_hash};
I agreed with @vlopes11, and honestly I don't see here the difference from having:
```rust
use zelbet::sponge;

sponge::gadget(…)
sponge::hash(…)
```

I think it's perfectly fine avoiding the aliases here.

2022-03-23 14:45 UTC, ZER0 commented on src/gadget.rs
> +pub(crate) use concrete::concrete;
I think you made it backwards. So the original was:
```rust
use bar::bar_gadget;
use brick::brick_gadget;
use concrete::concrete_gadget;
```

As you can see, the duplicated term here is the module name, not the `gadget` part.

So if you have just `gadget` exported from the module, you can use:

```rust
    for round in 0..3 {
        concrete::gadget(composer, &mut state, round);
        brick::gadget(composer, &mut state);
    }
```

you won't even need a re-export (and, in case you *really* need it, that would be the right time to use aliases, since `gadget` will clash).

2022-03-23 14:45 UTC, ZER0 commented on src/gadget/bar.rs
> +    use crate::hash::bar as bar_hash;
In term of module, this is a bit weird. If the `bar` function is indeed an `hash` function, then you should have: `use crate::bar::hash` as we have for the gadgets.

2022-03-23 14:45 UTC, ZER0 commented on src/gadget/brick.rs
> +                brick_hash(&mut state);
Given the comments I made before, that would looks like:
```rust
                // Get result from brick gadget
                brick::gadget(composer, &mut state_gadget);
                // Get result from brick
                brick::hash(&mut state)
```

But that's only if the brick, bar, and concrete are considered hash functions, otherwise I believe the structure should be different (and definitely we shouldn't have `brick_hash`).

2022-03-23 14:45 UTC, ZER0 commented on src/sponge.rs
> +use crate::hash as zelbet_hash;
Again, aliases only if / when needed.
You could just do `crate::gadget` instead of `zelbet_gadget` or, if it makes the code more readable later, you can just aliases the current crate:

```
use crate as zelbet;
```

So that you can later on call `zelbet::gadget`.

2022-03-23 14:45 UTC, ZER0 commented on tests/zelbet.rs
> +use zelbet::{gadget as zelbet_gadget, hash as zelbet_hash};
Same here.

2022-03-23 15:18 UTC, moCello commented on src/gadget.rs
> +pub(crate) use concrete::concrete;
I see where you are getting here, but this change needs an even bigger restructure of the modules, where the split between hash and gadget happens in the same file at the end of the module tree. I'll draft a new version

2022-03-30 23:36 UTC, vlopes11 approved these changes
LGTM! Its much cleaner now

2022-03-31 11:03 UTC, merged