Refactor/Fix sponge function
dusk-network/zelbet pull request #63
Opened 2022-04-25 12:19 UTC by moCello

I used the change in the function signatures for issue #50 to also refactor sponge internally to make it easier to follow.

The capacity of the state was initialized with a one but it must be a zero -> Fixed

We used to have sponge return an output vector of variable length. However in our use case this output vector will always be one element long. We therefore decided to remove complexity and get rid of the `output_len` parameter. We will always return one `BlsScalar`.
See also the discussion bellow

2022-05-04 04:13 UTC, vlopes11 requested changes

2022-05-04 04:13 UTC, vlopes11 commented on src/sponge.rs
> +pub fn hash(input: &[BlsScalar], output_len: usize) -> Vec<BlsScalar> {
There is something off with this function. Normally we use a single bit digest as output:

`pub fn hash(input: &[BlsScalar]) -> BlsScalar`

Here we are mixing functionalities. You are creating an iterator that could squeeze `n` elements, while also providing a normal digest function.

I suggest you split this function in two:

`pub fn digest(input: &[BlsScalar]) -> BlsScalar`
`pub fn stream(input: &[BlsScalar]) -> impl Iterator<Item = BlsScalar>`

2022-05-04 04:15 UTC, vlopes11 commented on src/sponge.rs
> +pub fn hash(input: &[BlsScalar], output_len: usize) -> Vec<BlsScalar> {
There is something off with this function. Normally we use a single bit digest as output:

`pub fn hash(input: &[BlsScalar]) -> BlsScalar`

Here we are mixing functionalities. You are creating an iterator that could squeeze `n` elements, while also providing a normal digest function.

I suggest you split this function in two:

`pub fn digest(input: &[BlsScalar]) -> BlsScalar`
`pub fn stream(input: &[BlsScalar]) -> impl Iterator<Item = BlsScalar>`

2022-05-04 04:15 UTC, vlopes11 commented on src/sponge.rs
> +pub fn hash(input: &[BlsScalar], output_len: usize) -> Vec<BlsScalar> {
For that, you will need some iterator wrapper struct that will contain a state and its used element

2022-05-04 08:40 UTC, moCello commented on src/sponge.rs
> +pub fn hash(input: &[BlsScalar], output_len: usize) -> Vec<BlsScalar> {
Not sure I understand what you mean. I follow the sponge framework that is divided in three phases:
- Pad `input`
- Absorb `input` into `state`
- Squeeze `state` to generate `output` of the given length `output_len`

I could of course create three different functions for those phases but I don't really see what is being achieved with that. But maybe I am missing your point.

2022-05-04 08:43 UTC, moCello commented on src/sponge.rs
> +pub fn hash(input: &[BlsScalar], output_len: usize) -> Vec<BlsScalar> {
We talked earlier about the output of sponge. It actually can be of different length which is why we have `output_len` as a parameter. If we decide however that we want ours to always return one `BlsScalar` I could of course change that.

2022-05-04 09:18 UTC, vlopes11 commented on src/sponge.rs
> +pub fn hash(input: &[BlsScalar], output_len: usize) -> Vec<BlsScalar> {
We are talking specifically about the `squeeze` phase. The `pad` and `absorb` is fine

Yes, the output might be variable size. However, many use cases will only get one field element; so its a waste to create a vector to store a single element.

As for the variable size, if we are creating a vector, we are eager loading and allocating unnecessarily. If its an iterator, the consumer can decide what to do with that (including creating a vector with `collect::<Vec<BlsScalar>>`

2022-05-04 09:49 UTC, moCello commented on src/sponge.rs
> +pub fn hash(input: &[BlsScalar], output_len: usize) -> Vec<BlsScalar> {
Ok, I see. I think you are right then and the easiest would be to simply return one `BlsScalar` so we don't introduce complexity that we don't use anyway.

2022-05-04 10:15 UTC, vlopes11 commented on src/sponge.rs
> +pub fn hash(input: &[BlsScalar], output_len: usize) -> Vec<BlsScalar> {
We might use multiple outputs of the sponge tho. We could leave an open issue to implement the iterator in the future

2022-05-04 10:35 UTC, moCello commented on src/sponge.rs
> +pub fn hash(input: &[BlsScalar], output_len: usize) -> Vec<BlsScalar> {
Sure! Although given the fact that we didn't need sponge to return multiple outputs up until this point, I find it unlikely that we will need it in the future. But one never knows.

2022-05-10 08:52 UTC, vlopes11 approved these changes
LGTM

2022-05-10 08:52 UTC, vlopes11 commented on src/sponge.rs
> +    let mut input = input.to_vec();
As improvement for the future (or now), this can easily be an iterator instead of a vector

2022-05-10 08:52 UTC, vlopes11 commented on tests/sponge.rs
>  fn sponge_circuit(composer: &mut TurboComposer, input: BlsScalar) {
Also for the future, but it doesn't really make sense to test a sponge function with a single scalar. This test should cover edge cases such as 0, 1, 2 and many scalars as input

2022-05-11 17:02 UTC, moCello commented on tests/sponge.rs
>  fn sponge_circuit(composer: &mut TurboComposer, input: BlsScalar) {
Good point! I will add more test cases

2022-05-11 17:03 UTC, moCello commented on src/sponge.rs
> +    let mut input = input.to_vec();
You are right, I'll change it now

2022-05-12 07:20 UTC, ureeves approved these changes
LGTM

2022-05-13 12:16 UTC, vlopes11 approved these changes
LGTM

2022-05-16 09:44 UTC, merged