Update `dusk-plonk` dependency to `plonkup`
dusk-network/zelbet pull request #81
Opened 2022-10-03 13:18 UTC by moCello

2022-10-20 13:29 UTC, ZER0 requested changes
Overall looks good, there is few nits; but mostly I mark as request change for two main reason:
- The `alloc` commented out
- The bench are not compiling at all (is that known?)

As separate note, looks like you're not locally running clippy, since I noticed a lot of small things that clippy would have definitely catch; but I didn't report them, since are not strictly related to the PR. My suggestion would be open an issue to add `clippy` to the CI, as we have in other repo, and fixes all the nits that make sense (or `allow` the one they doesn't).

2022-10-20 13:29 UTC, ZER0 commented on CHANGELOG.md
> +- Port crate from `plonk` v0.9 to `plonkup` v0.1 [#80]
Nit: It should start with either `Change` or one of the aliases we normally use (e.g. `Rename`, `Update`…)

2022-10-20 13:29 UTC, ZER0 commented on benches/merkle.rs
> +use plonkup::error::Error as PlonkError;
I think we probably need to rename this `PlonkupError` as well.

2022-10-20 13:29 UTC, ZER0 commented on src/components/bars/compose.rs
> +        let expected = super::native(decomp);
You can also use shadowing when you're not using anymore a variable.
Having something like this:
```rust
        let expected = [
            678, 674, 683, 687, 690, 660, 689, 686, 692, 678, 661, 668, 686,
            662, 680, 666, 672, 684, 669, 683, 687, 682, 674, 663, 673, 660,
            656,
        ];
        
        let expected = super::native(expected);
```

is perfectly idiomatic.

2022-10-20 13:29 UTC, ZER0 commented on src/components/bars/compose.rs
> +        assert_eq!(expected, -BlsScalar::from(5));
Remember that `assert*` macro also takes an additional parameter that works as "context"; it's useful because it give context to both the reader / maintainer and in the logging.

2022-10-20 13:29 UTC, ZER0 commented on src/components/concrete.rs
>  #[cfg(test)]
Are these actually unit test? E.g. are they accessing to internals of the module (in this case `concrete`) that are not exposed to the library's consumer?

2022-10-20 13:29 UTC, ZER0 commented on src/lib.rs
>  // #[cfg(feature = "alloc")]
I think this is either a left-over or a mistake.

2022-10-20 13:29 UTC, ZER0 commented on tests/merkle.rs
> +use plonkup::error::Error as PlonkError;
Ditto.

2022-10-20 13:29 UTC, ZER0 commented on tests/merkle.rs
> +        let leaf = composer.append_witness(*self.branch.deref());
I don't think you need `deref()` here.

2022-10-21 12:30 UTC, moCello commented on src/components/bars/compose.rs
> +        let expected = super::native(decomp);
That is true, but is anything gained in the above case? I would argue that here it is adding confusion since the array is not the expected value, but its decomposition.

2022-10-21 12:33 UTC, moCello commented on src/components/concrete.rs
>  #[cfg(test)]
Yes, everything in the `components` module is only public within the crate and needs to be tested internally

2022-10-21 14:13 UTC, moCello commented on src/components/bars/compose.rs
> +        assert_eq!(expected, -BlsScalar::from(5));
What would you suggest for context?

2022-11-07 09:38 UTC, ZER0 commented on tests/merkle.rs
> +    };
While there is nothing technically wrong with that, I would rather derive `Default` for `MerkleOpeningCircuit` since all its member implement `Default`, and having here just:
```rust
let mut circuit = MerkleOpeningCircuit::default();
```

2022-11-07 09:38 UTC, ZER0 commented on src/components/bars/compose.rs
> +        let expected = super::native(decomp);
It gains a reduction of pollution of different variables, and a clear statement (for the developer) that from that point on the previous one `composition` is not used anymore. Shadowing can be problematic when they're across pages of code, but if they're don in the same visual block there is no confusion in that sense, it actually helps.

2022-11-07 09:41 UTC, ZER0 commented on src/components/bars/compose.rs
> +        assert_eq!(expected, -BlsScalar::from(5));
I would add what you're asserting here. There is no context, however you added a comment above if I'm not mistaken saying `// Check if -5 is composed correctly`. That is the context, whatever this assert is here for.

2022-11-07 09:43 UTC, ZER0 approved these changes
LGTM there a very minor nit about the default, but since it's just for testing it's up to you if you want to fix it before merging (I would do, you basically have to add only a `#derive(Default)` and remove few lines of code, that is always a good thing, improving readability in the meantime).

2022-11-07 10:37 UTC, merged